package org.sid.projet_hps.dtos;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class AdditionalDataDTO {
    private String mappingServiceAccountNumber;
    private String gcmsProductIdentifier;
    private String licensedProductIdentifier;
    private String fundingAccountInformation;
    private String messageErrorIndicator;
    private String digitalAccountReferenceNumber;
    private String clearingCurrencyConversionIdentifier;
    private String currencyConversionDate;
    private String currencyConversionIndicator;
    private String transactionIntegrityClass;
    private String acceptanceData;
    private String digitalCommerceSolutionsIndicators;
    private String transactionTypeIndicator;
    private String additionalTerminalOperatingEnvironments;
    private String terminalType;
    private String messageReversalIndicator;
    private String flexCode;
    private String receivingAccountNumber;
    private String qrDynamicCodeData;
    private String transactionTypeIdentifier;
    private String programParticipationIndicator;
    private String generatedInstallmentIdentifier;
    private String japanCommonMerchantCode;
    private String electronicCommerceSecurityLevelIndicator;
    private String electronicCardIndicator;
    private String transactionCategoryIndicator;
    private String tokenAssuranceLevel;
    private String tokenRequestorId;
    private String financialAccountInformation;
    private String conversionServiceIndicator;
    private String authenticationIndicator;
    private double taxAmount;
    private double cardholderBillingAmountUSD;
    private double currencyConversionAssessmentAmountUSD;
    private String customerCurrencyConversionRevenueData;
    private double alternateTransactionFeeAmount;
    private double transactionFeeAmounts;
    private double extendedPrecisionAmounts;
    private String currencyExponents;
    private String originalAmountCurrencyCodes;
    private String alternateProcessorIndicator;
    private String businessActivity;
    private String centralSiteBusinessDate;
    private String businessCycle;
    private String acceptorClassificationOverrideIndicator;
    private String productOverrideIndicator;
    private String corporateIncentiveRatesApplyIndicator;
    private String specialConditionsIndicator;
    private String assignedIdOverrideIndicator;
    private String accountCategoryCode;
    private String rateIndicator;
    private String incentiveIndicator;
    private String interchangeOverrideIndicator;
    private String settlementData;
    private String multipleSettlementData;
    private String settlementIndicator;
    private String settlementInformation;
    private String inquiryInformation;
    private String alternateAcceptorDescription;
    private String soleProprietorName;
    private String legalCorporateName;
    private String dunAndBradstreetNumber;
    private String acceptorUrl;
    private String assignedId;
    private String crossBorder;
    private String alternateAcceptorDescriptionData2;
    private String longRunningTransactionIndicator;
    private String domesticAcceptorTaxId;
    private String installmentPaymentData;
    private String installmentPaymentCardholderStatementData;
    private String postDatedTransactionData;
    private String directoryServerTransactionId;
    private String accountholderAuthenticationValue;
    private String programProtocol;
    private String proprietaryInControlData;
    private String pointOfInteractionPhoneData;
    private String partnerIdCode;
    private String originatingMessageFormat;
    private String paymentTransactionInitiator;
    private String remotePaymentProgramDate;
    private String installmentData;
    private String mobilePhoneReloadData;
    private String nationalUseTaxData;
    private String deviceType;
    private String panSyntaxError;
    private String amountSyntaxError;
    private String syntaxReturnMessageErrorIndicator;
    private String latePresentmentIndicator;
    private String walletIdentifier;
    private String additionalMerchantData;
    private String independentSalesOrganizationId;
    private String transitProgram;
    private String terminalCompliantIndicator;
    private String merchantCountryOfOrigin;
    private String additionalAcceptorData;
    private String cardholderMerchantInitiatedTransactionIndicator;
    private String merchantTaxId;
    private String domesticMerchantTaxId;
    private String syntaxReturnOriginalMessageReasonCode;
    private String riskManagementApprovalCode;
}
